extends:
  - eslint:recommended
  - plugin:react/recommended
  - react-app
  - airbnb
rules:
  react/jsx-filename-extension: 0
  react/function-component-definition: 0
  react/jsx-props-no-spreading: 0
  import/extensions: 0
  react/prop-types: 0