extends:
  - eslint:recommended
  - plugin:react/recommended
  - react-app
  - airbnb
  - airbnb-typescript
parserOptions:
  project:
    - ./tsconfig.json
rules:
  react/jsx-filename-extension: 0
  react/function-component-definition: 0
  react/prop-types: 0