# env:
#   browser: true
#   es2021: true
# extends:
#   - eslint:recommended
#   - plugin:react/recommended
#   - airbnb-base
# parserOptions:
#   ecmaFeatures:
#     jsx: true
#   ecmaVersion: latest
#   sourceType: module
# plugins:
#   - react
# rules: 
#   import/extensions: 0
#   import/prefer-default-export: 0
#   react/prop-types: 0
#   react-hooks/exhaustive-deps: 0
#   no-param-reassign: 0